import "./RiskFactorsPanel.css";

function drainageStatus(pct) {
  if (pct >= 80) return { label: "Near Capacity", colorVar: "--color-risk-critical" };
  if (pct >= 60) return { label: "Elevated Load", colorVar: "--color-risk-high" };
  if (pct >= 35) return { label: "Moderate Load", colorVar: "--color-risk-moderate" };
  return { label: "Normal", colorVar: "--color-risk-low" };
}

function runoffColorVar(level) {
  if (level === "Very High") return "--color-risk-critical";
  if (level === "High") return "--color-risk-high";
  if (level === "Moderate") return "--color-risk-moderate";
  return "--color-risk-low";
}

export default function RiskFactorsPanel({ selected }) {
  if (!selected) return null;
  const drainage = drainageStatus(selected.drainageCapacityUsed);

  const factors = [
    {
      label: "Rainfall Intensity",
      value: selected.rainfallIntensity,
      unit: "mm/hr",
      note: "Current intensity at monitored gauge",
    },
    {
      label: "Water Level",
      value: selected.waterLevel.toFixed(1),
      unit: "m",
      note: "Primary drain / channel level",
    },
    {
      label: "Soil Saturation",
      value: selected.soilSaturation,
      unit: "%",
      note: "Ground infiltration capacity remaining is limited",
    },
  ];

  return (
    <section className="panel" aria-labelledby="risk-factors-heading">
      <div className="panel-header">
        <h2 id="risk-factors-heading">Flood-Risk Contributing Factors</h2>
      </div>
      <div className="panel-body factors-grid">
        {factors.map((f) => (
          <div className="factor-card" key={f.label}>
            <span className="eyebrow">{f.label}</span>
            <div className="factor-card__value">
              <span className="mono factor-card__number">{f.value}</span>
              <span className="factor-card__unit">{f.unit}</span>
            </div>
            <p className="factor-card__note">{f.note}</p>
          </div>
        ))}

        <div className="factor-card">
          <span className="eyebrow">Drainage Capacity Used</span>
          <div className="factor-card__value">
            <span className="mono factor-card__number">{selected.drainageCapacityUsed}</span>
            <span className="factor-card__unit">%</span>
          </div>
          <div className="factor-card__bar" role="img" aria-label={`Drainage capacity used ${selected.drainageCapacityUsed} percent`}>
            <div
              className="factor-card__bar-fill"
              style={{
                width: `${selected.drainageCapacityUsed}%`,
                background: `var(${drainage.colorVar})`,
              }}
            />
          </div>
          <p className="factor-card__note" style={{ color: `var(${drainage.colorVar})`, fontWeight: 600 }}>
            {drainage.label}
          </p>
        </div>

        <div className="factor-card">
          <span className="eyebrow">Surface Runoff</span>
          <div className="factor-card__value">
            <span className="factor-card__runoff" style={{ color: `var(${runoffColorVar(selected.surfaceRunoff)})` }}>
              {selected.surfaceRunoff}
            </span>
          </div>
          <p className="factor-card__note">Runoff generated by impervious urban surfaces</p>
        </div>
      </div>
    </section>
  );
}
